### ISSUE TITLE
Volatile internal error at Rules/LHS.hs:767

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#3652]
Internal error in Agda-2.6.0 87fb8278650472a3c9d93badd7888ced15b51240  with the following version of the standard library:
```
$ git submodule status
 f818c4089bd265a134775f66943cf9599444b235 std-lib (v1.0)
```
The following code triggers an internal error at `src/full/Agda/TypeChecking/Rules/LHS.hs:767`:
```agda
{-# OPTIONS --without-K #-}

module _ where

open import Data.Fin.Substitution
open import Data.Nat hiding (_⊔_)
open import Data.Fin using (Fin; zero; suc; lift)
open import Data.Vec
import Data.Vec.Properties as VecProp
open import Function as Fun using (_∘_; _$_)
open import Relation.Binary.PropositionalEquality as PropEq
  using (_≡_; refl; sym; cong; cong₂)
open PropEq.≡-Reasoning
open import Level using (Level; _⊔_)
open import Relation.Unary using (Pred)

lift-commutes : ∀ {n} k j (x : Fin (j + (k + n))) →
                lift j suc (lift j (lift k suc) x) ≡
                lift j (lift (suc k) suc) (lift j suc x)
lift-commutes k zero    x       = refl
lift-commutes k (suc j) zero    = refl
lift-commutes k (suc j) (suc x) = cong suc (lift-commutes k j x)

record Lemmas₀ {ℓ : Level} (T : Pred ℕ ℓ) : Set ℓ where
  field simple : Simple T

  open Simple simple

  extensionality : ∀ {m n} {ρ₁ ρ₂ : Sub T m n} →
                   (∀ x → lookup ρ₁ x ≡ lookup ρ₂ x) → ρ₁ ≡ ρ₂
  extensionality {ρ₁ = []}      {[]}       hyp = refl
  extensionality {ρ₁ = t₁ ∷ ρ₁} { t₂ ∷ ρ₂} hyp with hyp zero
  extensionality {ρ₁ = t₁ ∷ ρ₁} {.t₁ ∷ ρ₂} hyp | refl =
    cong (_∷_ t₁) (extensionality (hyp ∘ suc))

  id-↑⋆ : ∀ {n} k → id ↑⋆ k ≡ id {k + n}
  id-↑⋆ zero    = refl
  id-↑⋆ (suc k) = begin
    (id ↑⋆ k) ↑ ≡⟨ cong _↑ (id-↑⋆ k) ⟩
    id        ↑ ∎

  lookup-map-weaken-↑⋆ : ∀ {m n} k x {ρ : Sub T m n} →
                         lookup (map weaken ρ ↑⋆ k) x ≡
                         lookup ((ρ ↑) ↑⋆ k) (lift k suc x)
  lookup-map-weaken-↑⋆ zero    x           = refl
  lookup-map-weaken-↑⋆ (suc k) zero        = refl
  lookup-map-weaken-↑⋆ (suc k) (suc x) {ρ} = begin
    lookup (map weaken (map weaken ρ ↑⋆ k)) x        ≡⟨ VecProp.lookup-map x weaken _ ⟩
    weaken (lookup (map weaken ρ ↑⋆ k) x)            ≡⟨ cong weaken (lookup-map-weaken-↑⋆ k x) ⟩
    weaken (lookup ((ρ ↑) ↑⋆ k) (lift k suc x))      ≡⟨ sym $ VecProp.lookup-map (lift k suc x) _ _ ⟩
    lookup (map weaken ((ρ ↑) ↑⋆ k)) (lift k suc x)  ∎

record Lemmas₁ {ℓ} (T : Pred ℕ ℓ) : Set ℓ where
  field lemmas₀ : Lemmas₀ T

  open Lemmas₀ lemmas₀
  open Simple simple

  field weaken-var : ∀ {n} {x : Fin n} → weaken (var x) ≡ var (suc x)

  postulate
    lookup-map-weaken : ∀ {m n} x {y} {ρ : Sub T m n} →
                        lookup             ρ  x ≡ var      y →
                        lookup (map weaken ρ) x ≡ var (suc y)

  lookup-wk : ∀ {n} (x : Fin n) → lookup wk x ≡ var (suc x)
  lookup-wk x = lookup-map-weaken x ?
```
My attempts at shrinking have not been very successful.

**Comment by jespercockx** [comment]
I have pushed a patch that (hopefully) fixes the build for now. However, it is still possible to trigger the internal error by changing the definition of `lookup` in `Data.Vec` to
```
  lookup : ∀ {n} → Vec A n → Fin n → A
  lookup []       ()
  lookup (x ∷ xs) zero    = x
  lookup (x ∷ xs) (suc i) = lookup xs i
```
It seems that with this small change to the `lookup` function the internal error is also triggered without the recent changes to the coverage checker.

**Comment by UlfNorell** [comment]
I cannot reproduce the internal error (even when rolling back 16bce9b, with or without `--ignore-interfaces`, cmdline or emacs). I get lots of yellow constraints on `lookup` though. I think is because when you split on the vector first `lookup ?X y` is blocked, but if you split on the Fin first, it's a neutral term. The latter allows more constraint solving.

**Comment by asr** [comment]
> I have pushed a patch that (hopefully) fixes the build for now.

I noted the error with GHC 7.10.3 in [Travis](https://www.travis-ci.org/agda/agda/jobs/512040618):

```
src/full/Agda/TypeChecking/CompiledClause.hs:182:32:
    No instance for (Semigroup Doc) arising from a use of ‘<>’
    In the first argument of ‘(<?>)’, namely ‘("done" <> pretty hs)’
    In the expression: ("done" <> pretty hs) <?> pretty t
    In an equation for ‘pretty’:
        pretty (Done hs t) = ("done" <> pretty hs) <?> pretty t
```

I'm testing a fix in my machine right now...

**Comment by UlfNorell** [comment]
That one is my bad. Sorry.

**Comment by UlfNorell** [comment]
Here's the difference in constraint solving for the two versions of `lookup`. This is with the stopgap commit in place (otherwise both definitions turn into `lookup₂`):

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Equality

variable
  n : Nat
  A : Set

data Fin : Nat → Set where
  zero : Fin (suc n)
  suc  : Fin n → Fin (suc n)

data Vec (A : Set) : Nat → Set where
  []  : Vec A 0
  _∷_ : A → Vec A n → Vec A (suc n)

variable
  xs : Vec A n
  i  : Fin n

-- Splits on the Fin first
lookup₁ : Vec A n → Fin n → A
lookup₁ (x ∷ xs)  zero   = x
lookup₁ (x ∷ xs) (suc i) = lookup₁ xs i

-- Splits on the Vec first
lookup₂ : Vec A n → Fin n → A
lookup₂ []       ()
lookup₂ (x ∷ xs) zero    = x
lookup₂ (x ∷ xs) (suc i) = lookup₂ xs i

test₁ : lookup₁ _ i ≡ lookup₁ xs i
test₁ = refl

test₂ : lookup₂ _ i ≡ lookup₂ xs i
test₂ = refl -- yellow

test₃ : lookup₁ xs _ ≡ lookup₁ xs i
test₃ = refl -- yellow

test₄ : lookup₂ xs _ ≡ lookup₂ xs i
test₄ = refl
```
It would be nice if we could detect that all these calls are neutral, but this is a bigger change than I'm willing to undertake before the release.

**Comment by asr** [comment]
I pushed the commit fixing the building error with GHC 7.10.3, so Travis should be green in a while.

**Comment by jespercockx** [comment]
> I cannot reproduce the internal error (even when rolling back 16bce9b, with or without --ignore-interfaces, cmdline or emacs). I get lots of yellow constraints on lookup though. I think is because when you split on the vector first lookup ?X y is blocked, but if you split on the Fin first, it's a neutral term. The latter allows more constraint solving.

Likewise, after updating to the latest commit I cannot reproduce the internal error anymore even without 16bce9b. Maybe it got fixed by @UlfNorell in 29a27580013292ae57fca08e064d643838fd6e62 somehow?

Regarding the unsolved constraints, it seems to me we have three options:

1. Roll back everything related to allowing skipping of absurd clauses, up to and including https://github.com/agda/agda/commit/242684bca62fabe43e125aefae7526be4b26a135
2. Keep the situation as it is now: this will result in some unsolved constraints where there weren't before, but the opposite is also true (some constraints may be solved now which weren't solved before). In particular, we need to update the standard library so it checks with this change.
3. Some intermediate solution (e.g. rolling back the more recent changes but not my initial patch). We don't change which constraints are solved, but breaks the invariant that case splitting shouldn't result in missing clauses.

I'm in favour of option 2.

**Comment by gallais** [comment]
> but breaks the invariant that case splitting shouldn't result in missing clauses.

It only breaks the invariant if we do include #3533, doesn't it? Otherwise we have
the old splitting strategy which may be too verbose but should produce valid covers.
I agree with @andreasabel in #3650: we should just roll back #3533 an try to ship
it in 2.6.1 after extensive testing instead (i.e. re-merge it back in right after
2.6.0 is released and catch all the bugs we can find by using it ourselves on real
projects).

**Comment by jespercockx** [comment]
> It only breaks the invariant if we do include #3533, doesn't it?

No, the invariant was already broken before that. The only difference is that with #3533, you're much more likely to actually get into a situation where the problem occurs. So just rolling back that PR doesn't really fix anything IMHO.

**Comment by UlfNorell** [comment]
I'm also in favour of option 2. The current behaviour is the right one, and with the internal error fixed there is no evidence of any bugs. It seems backwards to release a version with known issues just because we are afraid that there might be unknown issues in the fixed version.

**Comment by jespercockx** [comment]
I made a PR with the required changes to the standard library to make it check with the alternative splitting strategy of #3650: https://github.com/agda/agda-stdlib/pull/673

**Comment by MatthewDaggitt** [comment]
Merged in the PR, and fast-forwarded the standard library on master (26835b4)

**Comment by jespercockx** [comment]
Thanks!
