### ISSUE TITLE
Instance resolution should not require type annotations in unambiguous situations

### ISSUE THREAD

**Issue by mietek** [agda/agda#5349]
It seems that Agda 2.6.1.3 or earlier has introduced a regression with regards to instance resolution.  A whole lot of my code that previously typechecked now needs additional type annotations in situations that do not seem like they should require such annotations.

Arjen confirms the failure happens also in Agda 2.6.2-4f87d39.

```agda
data Type : Set where
  *   : Type
  _⊃_ : Type → Type → Type

record Model : Set₁ where
  field
    W   : Set
    V   : W → Set
    _≤_ : W → W → Set

open Model {{…}}

module Works where
  _⊩_ : ∀ {{M : Model}} → W → Type → Set
  w ⊩ *       = V w
  w ⊩ (A ⊃ B) = ∀ {w′ : W} → w′ ≤ w → w′ ⊩ A → w′ ⊩ B

module UsedToWork where
  _⊩_ : ∀ {{M : Model}} → W → Type → Set
  w ⊩ *       = V w
  w ⊩ (A ⊃ B) = ∀ {w′} → w′ ≤ w → w′ ⊩ A → w′ ⊩ B

{-
_39 : Set  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,20-22 ]
_r_41 : Model  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,29-30 ]
_M_47 : Model  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,38-39 ]
_M_51 : Model  [ at /Users/mietek/Desktop/InstanceResolutionRegression.agda:21,47-48 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  Resolve instance argument
    _M_47
      : ⦃ M = M₁ : Model ⦄ (w₁ : Model.W M₁) (A₁ B₁ : Type)
        {w′ = w′₁ : _39 (w = w₁) (A = A₁) (B = B₁)} →
        Model
  No candidates yet
  Resolve instance argument
    _r_41
      : ⦃ M = M₁ : Model ⦄ (w₁ : Model.W M₁) (A₁ B₁ : Type)
        {w′ = w′₁ : _39 (w = w₁) (A = A₁) (B = B₁)} →
        Model
  No candidates yet
  Resolve instance argument
    _M_51
      : ⦃ M = M₁ : Model ⦄ (w₁ : Model.W M₁) (A₁ B₁ : Type)
        {w′ = w′₁ : _39 (w = w₁) (A = A₁) (B = B₁)} →
        Model
  No candidates yet
  _39 =< Model.W _M_51
  _39 =< Model.W _M_47
  Model.W M =< Model.W _r_41
  _39 =< Model.W _r_41
-}
```

**Comment by jespercockx** [comment]
This is not a bug but an intentional change to instance resolution to make it more stable when there are still unsolved metavariables in the context types, see https://github.com/agda/agda/issues/3358

**Comment by mietek** [comment]
@jespercockx, I don’t understand how this is not a bug.  In #3358, you are saying that there is some ambiguity about the type of `x`.  But here, I don’t see how the type of `w′` could be ambiguous.

In `_⊩_ : ∀ {{M : Model}} → W → Type → Set`, the instance argument `{{M : Model}}` is sufficient to make the type `W` unambiguous.  This line is accepted, and so `W` is fixed as `Model.W M`.

In `w ⊩ * = V w`, the type of `w` is still fixed as `Model.W M`, and this is sufficient to resolve `V` as `Model.V M`.

But I don’t understand what happens in `w ⊩ (A ⊃ B) = ∀ {w′} → w′ ≤ w → w′ ⊩ A → w′ ⊩ B`.  The type of `w` is still fixed as `Model.W M`, which should be sufficient to resolve `_≤_` as `Model._≤_ M`, which should result in the type of `w′` being unified with the type of `w`.  To me, there is no ambiguity here.

Can you explain, please?

**Comment by jespercockx** [comment]
I'd like to explain but now when I try your example again on the latest development version of Agda it actually just checks without any unsolved constraints. So it seems you were right and there *was* a bug, but it has since been fixed. I'm not sure which change it was, if anyone can track it down that'd be interesting.

**Comment by andreasabel** [comment]
I tested the example in the OP and it fails uniformly in Agda 2.6.0 - 2.6.3.  It succeeds with Agda 2.5.4 and earlier.
So I don't understand the outcome of this discussion.
@mietek : Did you check that the OP works with agda `master`? 
@jespercockx : Would you mind checking again?

**Comment by jespercockx** [comment]
I checked again with the example in the OP and I still do not get any unsolved constraints, so I am not sure what is going on.

**Comment by andreasabel** [comment]
I am getting this with 2.6.3 compiled today:
```
_39 : Set  [ at 21,20-22 ]
_r_41 : Model  [ at 21,29-30 ]
_M_47 : Model  [ at 21,38-39 ]
_M_51 : Model  [ at 21,47-48 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  Resolve instance argument _M_47 : Model No candidates yet
    (blocked on _39)
  Resolve instance argument _r_41 : Model No candidates yet
    (blocked on _39)
  Resolve instance argument _M_51 : Model No candidates yet
    (blocked on _39)
  _39 =< Model.W _M_51 (blocked on any(_39, _M_51))
  _39 =< Model.W _M_47 (blocked on any(_39, _M_47))
  Model.W M =< Model.W _r_41 (blocked on _r_41)
  _39 =< Model.W _r_41 (blocked on any(_39, _r_41))
```
And the last line (line 21) has lots of yellow on the rhs:
```agda
  w ⊩ (A ⊃ B) = ∀ {w′} → w′ ≤ w → w′ ⊩ A → w′ ⊩ B
```
The unsolved metas coincide exactly with the OP.

**Comment by jespercockx** [comment]
You're correct, I did something stupid. I can now reproduce the problem, here's a minimized example:
```agda
record Model : Set₁ where
  field
    W : Set
    f : W → W → Set

theModel : {{m : Model}} → Model
theModel {{m}} = m

test : ∀ {{M : Model}} → Model.W M → Set
test w = ∀ {w′} → Model.f theModel w′ w
```
Unsolved constraints:
```
_7 : Set  [ at 14,16-17 ]
_m_9 : Model  [ at 14,29-37 ]

———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  Resolve instance argument _m_9 : Model No candidates yet
    (blocked on _7)
  Model.W m =< _m_9 .Model.W (blocked on _m_9)
  _7 =< _m_9 .Model.W (blocked on any(_7, _m_9))
```
The last constraint `_7 =< _m_9 .Model.W` is a bit suspicious: it looks like it *should* be solvable, but something goes wrong in the occurs check.

**Comment by jespercockx** [comment]
With the flags `--show-implicit --show-identity-substitutions` the problem becomes a bit clearer:
```
———— Errors ————————————————————————————————————————————————
Failed to solve the following constraints:
  Resolve instance argument _m_9 : Model No candidates yet
    (blocked on _7)
  Model.W m =< _m_9 (w = w) {w′ = w′} .Model.W (blocked on _m_9)
  _7 (w = w) =< _m_9 (w = w) {w′ = w′} .Model.W
    (blocked on any(_7, _m_9))
```
So the reason why the constraint `_7 =< _m_9 .Model.W` does not get solved is because Agda has not yet ruled out that the metavariable `_m_9` might depend on `w'`. And Agda cannot prune the dependency of `_m_9` on `w'` since the meta occurs under the projection `.Model.W`, so pruning here might in theory lose solutions.

The *other* way that Agda could solve this constraint is through eta-expansion of `_m_9`. This seems a bit more promising since no pruning needs to happen. However, Agda refuses to eta-expand it because it is an *instance* meta. 

Now, it used to be the case that Agda would skip instance constraints if the instance meta in question was already solved, so eta-expanding an instance meta would be bad (since it is "solving" it in a technical sense). However, this is no longer the case, i.e. nowadays Agda performs instance search even if the meta is already solved. So I *believe* that this is just an artifact of old times and we can simply remove this restriction on eta-expansion.

**Comment by jespercockx** [comment]
~~Good news: it works.~~

**Comment by mietek** [comment]
What happened here?

**Comment by jespercockx** [comment]
I tried a solution and first thought it worked but then found out problems with it. You can find my attempt at https://github.com/jespercockx/agda/tree/issue5349.
