### ISSUE TITLE
Interleaved mutual and equality constructors

### ISSUE THREAD

**Issue by akaposi** [agda/agda#5362]
For the following code:
```agda
{-# OPTIONS --cubical #-}
open import Agda.Primitive
open import Cubical.Foundations.Prelude

interleaved mutual

  data A : Type
  data B : A → Type

  constructor 
    a : A
    b : B a
    c : B a → A
    d : B (c b)
    e : _≡_ {A = A} a (c b)
````
I get the following error:
~~~~
Not in scope:
  b at bug.agda:15,26-27 (did you mean 'B'?)
when scope checking b
~~~~

As it is clear from the previous line, `b` is in scope for the point constructor `d`, but for the equality constructor `e`.

I am using the development version of Agda.

**Comment by akaposi** [comment]
Here is a workaround with forward declarations:
~~~~agda
data A : Type
data B : A → Type

a' : A
b' : B a'
c' : B a' → A 

data A where
  a : A
  c : B a → A
  e : _≡_ {A = A} a (c' b')

data B where
  b : B a
  d : B (c b)

a' = a
b' = b
c' = c
~~~~

**Comment by gallais** [comment]
Equality constructors are not supported by the interleaved mutual syntax
as I implemented it. I guess #5356 may solve that as there won't be any
need to automatically figure out to which inductive family the constructor
should be associated.

**Comment by andreasabel** [comment]
> Equality constructors are not supported by the interleaved mutual syntax
> as I implemented it. I guess #5356 may solve that as there won't be any
> need to automatically figure out to which inductive family the constructor
> should be associated.

I am afraid this would not fix it; even if you do not use `constructor` but `data ... where`, 
```agda
interleaved mutual

  data A : Type
  data B : A → Type

  data A where
    a : A

  data B where
    b : B a

  data A where
    c : B a → A

  data B where
    d : B (c b)

  data A where
    e : _≡_ {A = A} a (c b)
```
then still `interleaved mutual` blocks are reduced to forward declarations, resulting in 
```agda
  data A : Type
  data B : A → Type

  data A where
    a : A
    c : B a → A
    e : _≡_ {A = A} a (c b)   -- b is not in scope

  data B where
    b : B a
    d : B (c b)
```
At least according to the user manual:
https://github.com/agda/agda/blame/master/doc/user-manual/language/mutual-recursion.lagda.rst#L83-L87

**Comment by akaposi** [comment]
Indeed, the problem is not specific to cubical. The following also doesn't typecheck as it cannot be reduced to forward declarations:
~~~~agda
  interleaved mutual
    data A : Type
    data B : A → Type

    constructor
      a : A
      c : B a → A
      b : B a
      d : B (c b) → A
~~~~

**Comment by outdatedcaveman** [comment]
Still present in Agda 2.7.0.1, and with the `data X where` form of `interleaved mutual` the restriction looks broader than the original report suggests — it is not specific to equality constructors.

**1. Point constructors are affected too.** In this form, a constructor of `B` is not in scope for *any* later block of `A`'s constructors:

```agda
{-# OPTIONS --cubical --safe #-}
module P where

open import Agda.Builtin.Cubical.Path

interleaved mutual

  data A : Set
  data B : A → Set

  data A where
    a0   : A
    wrap : (x : A) → B x → A

  data B where
    b0 : (x : A) → B x

  data A where
    wrapB : (x : A) → wrap x (b0 x) ≡ wrap x (b0 x) → A
```

gives

```
Not in scope:
  b0
when scope checking b0
```

and the equality-constructor version fails identically:

```agda
  data A where
    lawA : (x : A) → wrap x (b0 x) ≡ x
```

Note that `wrap : (x : A) → B x → A` is accepted, so a constructor of `A` may mention the *sort* `B`; it is `B`'s *constructors* that are never in scope. It looks as though all `data A where` blocks are collected and scope-checked at the position of the first one.

**2.** I could not get the `constructor`-block syntax from the original report to parse in 2.7.0.1 (`Parse error` at `constructor`) — quite possibly my mistake, but if that form has been retired then `data X where` is the only route and the above is the whole of the current behaviour.

**Why this matters in practice.** This is currently the one thing blocking a higher inductive-inductive presentation of the syntax of a dependent type theory with an *indexed* term sort:

```agda
  data Syn : Sort → Set                    -- contexts, types, substitutions
  data Tm  : Syn (arrT tyR n n) → Set      -- terms, indexed by their type
```

Everything else in the signature goes through, including `pair : (A : …) (σ : …) → Tm (subTy A σ) → Syn …` — which is exactly the case that works, since it mentions `Tm` only as a sort. The single law that cannot be stated is comprehension's η,

```agda
    pairη : (A : …) (ρ : …) → pair A (p1 A ρ) (p2 A ρ) ≡ ρ
```

because it applies `p2`, a constructor of `Tm`. Quantifying over the term instead of naming it (`… (t : Tm (subTy A (p1 A ρ))) → pair A (p1 A ρ) t ≡ ρ`) does parse, but it is unsound for the intended theory: it makes `pair` constant in its term argument, so comprehension forgets the term it comprehends.

So for this class of definitions the limitation is not a stylistic inconvenience — it is the difference between being able to state the theory and not. Happy to supply the full signature if a larger test case is useful.
