### ISSUE TITLE
Unexpected failure of instance resolution

### ISSUE THREAD

**Issue by omelkonian** [agda/agda#6976]
*Agda version: 2.6.4*
---

The changelog for 2.6.4 mentions:
> [Breaking] The algorithm for resolution of instance arguments has been simplified. It will now only rely on the type of instances to determine which candidate it should use, and no longer on their values.

Alas the following example shows a regression w.r.t. Agda-2.6.3; maybe the algorithm has been *over-simplified*?

```agda
module FILE1 where

_∋_ : (A : Set) → A → A
A ∋ x = x

it : {A : Set} → ⦃ A ⦄ → A
it ⦃ x ⦄ = x

postulate DecidableEquality : Set → Set

record DecEq (A : Set) : Set where
  field _≟_ : DecidableEquality A

module M where
  postulate A : Set; _≟_ : DecidableEquality A

instance
  -- DecEq-A : DecEq _
  DecEq-A = DecEq _ ∋ record {M}
    where putAnythingHere!! = Set

-- _ = DecEq A ∋ it where open M
```

```agda
-- FILE2
open import FILE1

_ = DecEq A ∋ it where open M
```
```bash
<MY_PATH>.agda:3,18-20
No instance of type DecEq A was found in scope.
when checking that the expression it has type DecEq A
```

Here are a couple of ways to make the error go away:
1. Include the (commented) `DecEq : _`  type signature, surely related to the changelog.
2. Include (an identical copy of) the unit test in FILE1. ~Somehow, triggering instance resolution in the initial module "assigns" the type to `DecEq-A` and afterwards the same example succeeds in FILE2! Very weird indeed.~
EDIT: In fact, putting **any** piece of code (e.g. `_ = Set`) at the end of FILE1 works :S
3. Removing the anything-goes `where` clause surprisingly works!

**Comment by jespercockx** [comment]
I get
```
No module Term in scope
when scope checking the declaration
  open Term
```
Did you forget to copy something for the example?

**Comment by omelkonian** [comment]
> I get
> ```
> No module Term in scope
> when scope checking the declaration
>   open Term
> ```
> Did you forget to copy something for the example?

Whooops, corrected now. (if only we had literate Agda comments...)

**Comment by jespercockx** [comment]
It looks like Agda adds `DecEq-A` to the set of instance candidates with an unknown head, and never updates it even after the head becomes known. The table of unknown instances is only used locally but not exported to other modules, as it is assumed that all metas are resolved in imported modules. It's weird that this did not happen in earlier versions of Agda though, something with the change to the resolution must have triggered it. I'll investigate further.

**Comment by jespercockx** [comment]
Oh I see, there is the function `resolveUnknownInstanceDefs` but it is only called inside `getInstanceDefs`. An easy fix would be to also call this function right before writing the interface file. Even better would be if we would remember the blocker that's preventing the type from being resolved, and creating a constraint for updating the instance once it becomes unblocked.

**Comment by jespercockx** [comment]
I've made a fix in #6978. I'm still not sure which change exactly triggered this though, it seems to me like this has existed forever.

**Comment by UlfNorell** [comment]
Should this go in 2.6.4.1? Or is that too risky?

**Comment by jespercockx** [comment]
> Should this go in 2.6.4.1? Or is that too risky?

I have no strong opinions, I'll let @andreasabel decide whether to merge this before or after the release of 2.6.4.1.

**Comment by andreasabel** [comment]
Since this was not on the 2.6.4.1 milestone, I missed this...

**Comment by andreasabel** [comment]
For PVP reasons, should not go in 2.6.4.2, but 2.6.5 or higher.
